import streamlit as st
import requests
from PIL import Image

API_URL = "http://127.0.0.1:8000/predict"

st.set_page_config(
    page_title="RetinaScan",
    page_icon="👁️",
    layout="centered"
)

st.title("👁️ RetinaScan")
st.subheader("Diabetic Retinopathy Detection using Deep Learning")

st.write(
    "Upload a retina fundus image and the model will predict the stage of diabetic retinopathy."
)

uploaded_file = st.file_uploader(
    "Choose a retina image",
    type=["png", "jpg", "jpeg"]
)

class_descriptions = {
    "No DR": "No diabetic retinopathy detected.",
    "Mild": "Mild signs of diabetic retinopathy.",
    "Moderate": "Moderate diabetic retinopathy detected.",
    "Severe": "Severe diabetic retinopathy detected.",
    "Proliferative DR": "Advanced diabetic retinopathy detected."
}

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    st.image(image, caption="Uploaded Retina Image", use_container_width=True)

    if st.button("Predict"):
        with st.spinner("Analyzing image..."):
            files = {
                "file": (
                    uploaded_file.name,
                    uploaded_file.getvalue(),
                    uploaded_file.type
                )
            }

            response = requests.post(API_URL, files=files)

        if response.status_code == 200:
            result = response.json()

            predicted_label = result["predicted_label"]
            confidence = result["confidence"]
            probabilities = result["probabilities"]

            st.success("Prediction completed!")

            st.markdown("### Result")
            st.write(f"**Predicted class:** {predicted_label}")
            st.write(f"**Confidence:** {confidence}%")
            st.write(f"**Interpretation:** {class_descriptions[predicted_label]}")

            st.markdown("### Class probabilities")

            for label, prob in probabilities.items():
                st.write(f"{label}: {prob * 100:.2f}%")
                st.progress(float(prob))

            st.warning(
                "This result is generated by an AI model and should not replace medical diagnosis."
            )

        else:
            st.error("Error while calling the API. Make sure FastAPI is running.")